/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetApiMapByName200Response,
    GetApiMapByName200ResponseFromJSON,
    GetApiMapByName200ResponseToJSON,
} from '../models/GetApiMapByName200Response';
import {
    type GetApiMapByName400Response,
    GetApiMapByName400ResponseFromJSON,
    GetApiMapByName400ResponseToJSON,
} from '../models/GetApiMapByName400Response';

export interface GetApiMapByNameRequest {
    /**
     * 
     */
    name: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApiMapByName without sending the request
     */
    async getApiMapByNameRequestOpts(requestParameters: GetApiMapByNameRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getApiMapByName().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/map/{name}`;
        urlPath = urlPath.replace('{name}', encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Parse a map by name
     */
    async getApiMapByNameRaw(requestParameters: GetApiMapByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetApiMapByName200Response>> {
        const requestOptions = await this.getApiMapByNameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetApiMapByName200ResponseFromJSON(jsonValue));
    }

    /**
     * Parse a map by name
     */
    async getApiMapByName(requestParameters: GetApiMapByNameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetApiMapByName200Response> {
        const response = await this.getApiMapByNameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiMaps without sending the request
     */
    async getApiMapsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/maps`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all map names
     */
    async getApiMapsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.getApiMapsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all map names
     */
    async getApiMaps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.getApiMapsRaw(initOverrides);
        return await response.value();
    }

}
