/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiMapByName200ResponseBounds
 */
export interface GetApiMapByName200ResponseBounds {
    /**
     * 
     */
    minX: number;
    /**
     * 
     */
    minY: number;
    /**
     * 
     */
    maxX: number;
    /**
     * 
     */
    maxY: number;
}

/**
 * Check if a given object implements the GetApiMapByName200ResponseBounds interface.
 */
export function instanceOfGetApiMapByName200ResponseBounds(value: object): value is GetApiMapByName200ResponseBounds {
    if (!('minX' in value) || value['minX'] === undefined) return false;
    if (!('minY' in value) || value['minY'] === undefined) return false;
    if (!('maxX' in value) || value['maxX'] === undefined) return false;
    if (!('maxY' in value) || value['maxY'] === undefined) return false;
    return true;
}

export function GetApiMapByName200ResponseBoundsFromJSON(json: any): GetApiMapByName200ResponseBounds {
    return GetApiMapByName200ResponseBoundsFromJSONTyped(json, false);
}

export function GetApiMapByName200ResponseBoundsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName200ResponseBounds {
    if (json == null) {
        return json;
    }
    return {
        
        'minX': json['minX'],
        'minY': json['minY'],
        'maxX': json['maxX'],
        'maxY': json['maxY'],
    };
}

export function GetApiMapByName200ResponseBoundsToJSON(json: any): GetApiMapByName200ResponseBounds {
    return GetApiMapByName200ResponseBoundsToJSONTyped(json, false);
}

export function GetApiMapByName200ResponseBoundsToJSONTyped(value?: GetApiMapByName200ResponseBounds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'minX': value['minX'],
        'minY': value['minY'],
        'maxX': value['maxX'],
        'maxY': value['maxY'],
    };
}

