/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiMapByName200ResponseVerticesInner
 */
export interface GetApiMapByName200ResponseVerticesInner {
    /**
     * 
     */
    x: number;
    /**
     * 
     */
    y: number;
}

/**
 * Check if a given object implements the GetApiMapByName200ResponseVerticesInner interface.
 */
export function instanceOfGetApiMapByName200ResponseVerticesInner(value: object): value is GetApiMapByName200ResponseVerticesInner {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function GetApiMapByName200ResponseVerticesInnerFromJSON(json: any): GetApiMapByName200ResponseVerticesInner {
    return GetApiMapByName200ResponseVerticesInnerFromJSONTyped(json, false);
}

export function GetApiMapByName200ResponseVerticesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName200ResponseVerticesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function GetApiMapByName200ResponseVerticesInnerToJSON(json: any): GetApiMapByName200ResponseVerticesInner {
    return GetApiMapByName200ResponseVerticesInnerToJSONTyped(json, false);
}

export function GetApiMapByName200ResponseVerticesInnerToJSONTyped(value?: GetApiMapByName200ResponseVerticesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

