/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiMapByName200ResponseThingsInner
 */
export interface GetApiMapByName200ResponseThingsInner {
    /**
     * 
     */
    x: number;
    /**
     * 
     */
    y: number;
    /**
     * 
     */
    angle: number;
    /**
     * 
     */
    type: number;
    /**
     * 
     */
    flags: number;
}

/**
 * Check if a given object implements the GetApiMapByName200ResponseThingsInner interface.
 */
export function instanceOfGetApiMapByName200ResponseThingsInner(value: object): value is GetApiMapByName200ResponseThingsInner {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('angle' in value) || value['angle'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('flags' in value) || value['flags'] === undefined) return false;
    return true;
}

export function GetApiMapByName200ResponseThingsInnerFromJSON(json: any): GetApiMapByName200ResponseThingsInner {
    return GetApiMapByName200ResponseThingsInnerFromJSONTyped(json, false);
}

export function GetApiMapByName200ResponseThingsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName200ResponseThingsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
        'angle': json['angle'],
        'type': json['type'],
        'flags': json['flags'],
    };
}

export function GetApiMapByName200ResponseThingsInnerToJSON(json: any): GetApiMapByName200ResponseThingsInner {
    return GetApiMapByName200ResponseThingsInnerToJSONTyped(json, false);
}

export function GetApiMapByName200ResponseThingsInnerToJSONTyped(value?: GetApiMapByName200ResponseThingsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
        'angle': value['angle'],
        'type': value['type'],
        'flags': value['flags'],
    };
}

