/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetApiMapByName200ResponseThingsInner } from './GetApiMapByName200ResponseThingsInner';
import {
    GetApiMapByName200ResponseThingsInnerFromJSON,
    GetApiMapByName200ResponseThingsInnerFromJSONTyped,
    GetApiMapByName200ResponseThingsInnerToJSON,
    GetApiMapByName200ResponseThingsInnerToJSONTyped,
} from './GetApiMapByName200ResponseThingsInner';
import type { GetApiMapByName200ResponseVerticesInner } from './GetApiMapByName200ResponseVerticesInner';
import {
    GetApiMapByName200ResponseVerticesInnerFromJSON,
    GetApiMapByName200ResponseVerticesInnerFromJSONTyped,
    GetApiMapByName200ResponseVerticesInnerToJSON,
    GetApiMapByName200ResponseVerticesInnerToJSONTyped,
} from './GetApiMapByName200ResponseVerticesInner';
import type { GetApiMapByName200ResponseBounds } from './GetApiMapByName200ResponseBounds';
import {
    GetApiMapByName200ResponseBoundsFromJSON,
    GetApiMapByName200ResponseBoundsFromJSONTyped,
    GetApiMapByName200ResponseBoundsToJSON,
    GetApiMapByName200ResponseBoundsToJSONTyped,
} from './GetApiMapByName200ResponseBounds';
import type { GetApiMapByName200ResponseLinedefsInner } from './GetApiMapByName200ResponseLinedefsInner';
import {
    GetApiMapByName200ResponseLinedefsInnerFromJSON,
    GetApiMapByName200ResponseLinedefsInnerFromJSONTyped,
    GetApiMapByName200ResponseLinedefsInnerToJSON,
    GetApiMapByName200ResponseLinedefsInnerToJSONTyped,
} from './GetApiMapByName200ResponseLinedefsInner';

/**
 * 
 * @export
 * @interface GetApiMapByName200Response
 */
export interface GetApiMapByName200Response {
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    vertices: Array<GetApiMapByName200ResponseVerticesInner>;
    /**
     * 
     */
    linedefs: Array<GetApiMapByName200ResponseLinedefsInner>;
    /**
     * 
     */
    things: Array<GetApiMapByName200ResponseThingsInner>;
    /**
     * 
     */
    bounds: GetApiMapByName200ResponseBounds;
}

/**
 * Check if a given object implements the GetApiMapByName200Response interface.
 */
export function instanceOfGetApiMapByName200Response(value: object): value is GetApiMapByName200Response {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('vertices' in value) || value['vertices'] === undefined) return false;
    if (!('linedefs' in value) || value['linedefs'] === undefined) return false;
    if (!('things' in value) || value['things'] === undefined) return false;
    if (!('bounds' in value) || value['bounds'] === undefined) return false;
    return true;
}

export function GetApiMapByName200ResponseFromJSON(json: any): GetApiMapByName200Response {
    return GetApiMapByName200ResponseFromJSONTyped(json, false);
}

export function GetApiMapByName200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'vertices': ((json['vertices'] as Array<any>).map(GetApiMapByName200ResponseVerticesInnerFromJSON)),
        'linedefs': ((json['linedefs'] as Array<any>).map(GetApiMapByName200ResponseLinedefsInnerFromJSON)),
        'things': ((json['things'] as Array<any>).map(GetApiMapByName200ResponseThingsInnerFromJSON)),
        'bounds': GetApiMapByName200ResponseBoundsFromJSON(json['bounds']),
    };
}

export function GetApiMapByName200ResponseToJSON(json: any): GetApiMapByName200Response {
    return GetApiMapByName200ResponseToJSONTyped(json, false);
}

export function GetApiMapByName200ResponseToJSONTyped(value?: GetApiMapByName200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'vertices': ((value['vertices'] as Array<any>).map(GetApiMapByName200ResponseVerticesInnerToJSON)),
        'linedefs': ((value['linedefs'] as Array<any>).map(GetApiMapByName200ResponseLinedefsInnerToJSON)),
        'things': ((value['things'] as Array<any>).map(GetApiMapByName200ResponseThingsInnerToJSON)),
        'bounds': GetApiMapByName200ResponseBoundsToJSON(value['bounds']),
    };
}

