/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiMapByName200ResponseLinedefsInner
 */
export interface GetApiMapByName200ResponseLinedefsInner {
    /**
     * 
     */
    v1: number;
    /**
     * 
     */
    v2: number;
    /**
     * 
     */
    flags: number;
    /**
     * 
     */
    special: number;
    /**
     * 
     */
    tag: number;
    /**
     * 
     */
    side: Array<any>;
}

/**
 * Check if a given object implements the GetApiMapByName200ResponseLinedefsInner interface.
 */
export function instanceOfGetApiMapByName200ResponseLinedefsInner(value: object): value is GetApiMapByName200ResponseLinedefsInner {
    if (!('v1' in value) || value['v1'] === undefined) return false;
    if (!('v2' in value) || value['v2'] === undefined) return false;
    if (!('flags' in value) || value['flags'] === undefined) return false;
    if (!('special' in value) || value['special'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('side' in value) || value['side'] === undefined) return false;
    return true;
}

export function GetApiMapByName200ResponseLinedefsInnerFromJSON(json: any): GetApiMapByName200ResponseLinedefsInner {
    return GetApiMapByName200ResponseLinedefsInnerFromJSONTyped(json, false);
}

export function GetApiMapByName200ResponseLinedefsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName200ResponseLinedefsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'v1': json['v1'],
        'v2': json['v2'],
        'flags': json['flags'],
        'special': json['special'],
        'tag': json['tag'],
        'side': json['side'],
    };
}

export function GetApiMapByName200ResponseLinedefsInnerToJSON(json: any): GetApiMapByName200ResponseLinedefsInner {
    return GetApiMapByName200ResponseLinedefsInnerToJSONTyped(json, false);
}

export function GetApiMapByName200ResponseLinedefsInnerToJSONTyped(value?: GetApiMapByName200ResponseLinedefsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'v1': value['v1'],
        'v2': value['v2'],
        'flags': value['flags'],
        'special': value['special'],
        'tag': value['tag'],
        'side': value['side'],
    };
}

