/* tslint:disable */
/* eslint-disable */
/**
 * DoomTS API
 * Development documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApiMapByName400Response
 */
export interface GetApiMapByName400Response {
    /**
     * 
     */
    success: GetApiMapByName400ResponseSuccessEnum;
    /**
     * 
     */
    error: Array<any>;
    /**
     * 
     */
    data: any | null;
}


/**
 * @export
 */
export const GetApiMapByName400ResponseSuccessEnum = {
    False: false,
} as const;
export type GetApiMapByName400ResponseSuccessEnum = typeof GetApiMapByName400ResponseSuccessEnum[keyof typeof GetApiMapByName400ResponseSuccessEnum];


/**
 * Check if a given object implements the GetApiMapByName400Response interface.
 */
export function instanceOfGetApiMapByName400Response(value: object): value is GetApiMapByName400Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    
    if (value['success'] !== false) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetApiMapByName400ResponseFromJSON(json: any): GetApiMapByName400Response {
    return GetApiMapByName400ResponseFromJSONTyped(json, false);
}

export function GetApiMapByName400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiMapByName400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': json['error'],
        'data': json['data'],
    };
}

export function GetApiMapByName400ResponseToJSON(json: any): GetApiMapByName400Response {
    return GetApiMapByName400ResponseToJSONTyped(json, false);
}

export function GetApiMapByName400ResponseToJSONTyped(value?: GetApiMapByName400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'data': value['data'],
    };
}

